{% set name = "dj-database-url" %}
{% set version = "2.1.0" %}
{% set sha256 = "f2042cefe1086e539c9da39fad5ad7f61173bf79665e69bf7e4de55fa88b135f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - django >=1.8

test:
  imports:
    - dj_database_url

about:
  home: https://github.com/jacobian/dj-database-url
  license: BSD-2-Clause
  license_family: BSD
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Use Database URLs in your Django Application.
  description: |
    This simple Django utility allows you to utilize the 12factor inspired 
    DATABASE_URL environment variable to configure your Django application.
  doc_url: https://github.com/jacobian/dj-database-url
  dev_url: https://github.com/jacobian/dj-database-url

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - xmnlab
