{% set name = "dj-database-url" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dj-database-url-{{ version }}.tar.gz
  sha256: ccf3e8718f75ddd147a1e212fca88eecdaa721759ee48e38b485481c77bca3dc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.7,<3.11
    - django >3.2

test:
  imports:
    - dj_database_url
  commands:
    - pip check
  requires:
    - pip
    
about:
  home: https://github.com/jacobian/dj-database-url
  license: BSD-2-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Use Database URLs in your Django Application.'
  description: |
    This simple Django utility allows you to utilize the 12factor inspired 
    DATABASE_URL environment variable to configure your Django application.
  doc_url: https://github.com/jacobian/dj-database-url
  dev_url: https://github.com/jacobian/dj-database-url

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - rxm7706
    - xmnlab
